[router] - Ruteo a Lacchain / BFA / RSK | MULT-55
ong-bitcoin-argentina/DIDI-SSI-Blockchain-manager pull request #3
Opened 2020-10-27 20:51 UTC by dbale-atix

### **Description**
Mapeo de prefijos a Blockchain con SC definido.

- MAINNET ==> did:ethr:  
- RSK ==> did:ethr:rsk:  
- LACCHAIN ==> did:ethr:lacchain:  
- BFA ==> did:ethr:bfa:  

**Funciones con ruteo:**  

```
addDelegate
validateDelegate
resolveDIDDocument

```
**Funciones modificadas**

```
createJWT
verifyJWT

```
### **Automated Tests passed**  
![image](https://user-images.githubusercontent.com/72987783/97998881-69777300-1dc9-11eb-979b-a42f10250c6d.png)

### ***YouTrack***
https://atixlabs.myjetbrains.com/youtrack/issue/MULT-55

2020-11-02 13:49 UTC, MatiasOS requested changes
Parece que le falta alcguna configuración al script de testing para correr
```bash
DIDI-SSI-Blockchain-manager$ npm run test

> @proyecto-didi/didi-blockchain-manager@1.0.4 test /home/loki/dev/bitcoin-arg/DIDI-SSI-Blockchain-manager
> jest

 FAIL  __tests__/jwt_test.js
  ● Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    /home/loki/dev/bitcoin-arg/DIDI-SSI-Blockchain-manager/BlockchainManager.ts:77
      static delegateType = delegateTypes.Secp256k1SignatureAuthentication2018;
                          ^

    SyntaxError: Unexpected token =

      1 | const Constants = require('../Constants');
    > 2 | const { BlockchainManager } = require('../BlockchainManager');
        |                               ^
      3 | const { Credentials } = require('uport-credentials');
      4 | 
      5 | const config = {

      at Runtime._execModule (node_modules/jest-runtime/build/index.js:1179:56)
      at Object.<anonymous> (__tests__/jwt_test.js:2:31)

```

2020-11-02 13:49 UTC, MatiasOS commented on BlockchainManager.ts
> +var web3 = null,
No usar `var`

2020-11-02 14:11 UTC, dbale-atix commented on BlockchainManager.ts
> +var web3 = null,
Hola Matias, esto lo cambio ahora y pusheo

2020-11-02 15:48 UTC, MatiasOS requested changes
Dentro de `getGasLimit` ¿Cuál es la razón de aplicar la función `Math.max` entre estimate y  21000? 21000 es el costo de una tx que solo envía crypto. La mayoría de las llamadas a Smart Contracts consumen mucho más que 21000.

En la función `getGasPrice`. No hardcodear el incremento de `1.1` , debe pasarse como parámetro. Además, `minimumGasPrice` no existe en todas las redes.

2020-11-02 15:48 UTC, MatiasOS commented on package.json
>    "dependencies": {
Revisar dependencias. `dependencies` no debe incluir paquetes utilizados durante los procesos de build y test

2020-11-02 15:48 UTC, MatiasOS commented on BlockchainManager.ts
> +    // throw new Error("Invalid Provider Prefix");
Remover comentarios sin valor

2020-11-02 15:48 UTC, MatiasOS commented on BlockchainManager.ts
> +      // throw new Error(error);
Remover comentarios sin valor

2020-11-02 16:12 UTC, MatiasOS commented on BlockchainManager.ts
>      validity: number = Constants.BLOCKCHAIN.DELEGATE_VALIDITY
`Constants.BLOCKCHAIN.DELEGATE_VALIDITY`. No existe dentro de `Constants.js`

2020-11-02 16:27 UTC, MatiasOS commented on BlockchainManager.ts
> +  // async resolveDidDocument(did: string, config: { providerConfig: any }) {
Remover comentarios sin valor

2020-11-03 14:38 UTC, dbale-atix commented
> Dentro de `getGasLimit` ¿Cuál es la razón de aplicar la función `Math.max` entre estimate y 21000? 21000 es el costo de una tx que solo envía crypto. La mayoría de las llamadas a Smart Contracts consumen mucho más que 21000.
> 
> En la función `getGasPrice`. No hardcodear el incremento de `1.1` , debe pasarse como parámetro. Además, `minimumGasPrice` no existe en todas las redes. En la [documentación](https://web3js.readthedocs.io/en/v1.3.0/web3-eth.html#getgasprice) existe el método getGasPrice.



> Dentro de `getGasLimit` ¿Cuál es la razón de aplicar la función `Math.max` entre estimate y 21000? 21000 es el costo de una tx que solo envía crypto. La mayoría de las llamadas a Smart Contracts consumen mucho más que 21000.
> 
> En la función `getGasPrice`. No hardcodear el incremento de `1.1` , debe pasarse como parámetro. Además, `minimumGasPrice` no existe en todas las redes. En la [documentación](https://web3js.readthedocs.io/en/v1.3.0/web3-eth.html#getgasprice) existe el método getGasPrice.

Lo del 21000 es porque es el minimo de transaccion
Pero a veces la funcion de estimar gas devuelve menos, entonces le ponemos ese rango para que nunca sea menos.

Por otro lado, le definimos una variable como gas_increment para poner en el env y que el 1.1 no sea hardcodeado
Y sacamos el minimumGasPrice

2020-11-06 21:48 UTC, closed without merging